export default ["Kuda Pegasus"
  , , "Naga Api"
  , , "Harimau Putih"
  , "Serigala Emas"
  , "Burung Hantu"
  , "Hantu Jeruk"
  , "Raksasa Batu"
  , "Kucing Hantu"
  , "Ular Emas"
  , "Singa Laut"
  , "Kelinci Ajaib"
  , "Harimau Ajaib"
  , "Ikan Terbang"
  , "Elang Perak"
  , "Ular Terbang"
  , "Manusia Ikan"
  , "Anjing Hitam"
  , "Kuda Terbang"
  , "Gajah Putih"
  , "Srigala Biru"
  , "Harimau Merah"
  , "Burung Emas"
  , "Singa Hitam"
  , "Burung Api"
  , "Ular Ajaib"
  , "Ikan Mas"
  , "Kelinci Emas"
  , "Anjing Ajaib"
  , "Kuda Putih"
  , "Serigala Perak"
  , "Harimau Biru"
  , "Burung Hantu"
  , "Naga Hijau"
  , "Kucing Ajaib"
  , "Ular Hitam"
  , "Ikan Hitam"
  , "Gajah Emas"
  , "Singa Perak"
  , "Harimau Hitam"
  , "Burung Perak"
  , "Naga Emas"
  , "Kuda Hitam"
  , "Serigala Emas"
  , "Harimau Putih"
  , "Kelinci Putih"
  , "Ikan Perak"
  , "Batu Bertuah"
  , "Cermin Ajaib"
  , "Pedang Sakti"
  , "Tongkat Sihir"
  , "Jubah Gaib"
  , "Mahkota Emas"
  , "Gelang Sakti"
  , "Kalung Ajaib"
  , "Piring Terbang"
  , "Cincin Emas"
  , "Mangkuk Sakti"
  , "Keris Keramat"
  , "Guci Sihir"
  , "Tas Ajaib"
  , "Obor Gaib"
  , "Bunga Mistis"
  , "Permata Ajaib"
  , "Topi Gaib"
  , "Sepatu Sakti"
  , "Kucing Hitam"
  , "Ular Perak"
  , "Gajah Hijau"
  , "Burung Putih"
  , "Naga Merah"
  , "Kuda Emas"
  , "Serigala Putih"
  , "Harimau Emas"
  , "Burung Hijau"
  , "Ikan Emas"
  , "Kucing Putih"
  , "Ular Emas"
  , "Gajah Biru"
  , "Singa Putih"
  , "Kelinci Merah"
  , "Anjing Putih"
  , "Harimau Hijau"
  , "Burung Merah"
  , "Naga Biru"
  , "Kuda Merah"
  , "Serigala Hitam"
  , "Kelinci Biru"
  , "Ikan Hijau"
  , "Kucing Merah"
  , "Ular Hijau"
  , "Gajah Merah"
  , "Burung Biru"
  , "Naga Putih"
  , "Kuda Hijau"
  , "Serigala Merah"
  , "Harimau Biru"
  , "Burung Hitam"
  , "Ikan Biru"
  , "Kucing Hijau"
  , "Ular Merah"
  , "Gajah Putih"
  , "Singa Biru"
  , "Kelinci Hijau"
  , "Anjing Merah"
  , "Harimau Perak"
  , "Burung Perak"
  , "Naga Hijau"
  , "Kuda Biru"
  , "Serigala Hijau"
  , "Kucing Biru"
  , "Ikan Merah"
  , "Ular Putih"
  , "Gajah Emas"
  , "Singa Hijau"
  , "Kelinci Emas"
  , "Anjing Hijau"
  , "Harimau Hijau"
  , "Burung Hijau"
  , "Naga Emas"
  , "Kuda Putih"
  , "Serigala Emas"
  , "Harimau Putih"
  , "Kelinci Putih"
  , "Ikan Perak"
  , "Kucing Hitam"
  , "Ular Perak"
  , "Gajah Hijau"
  , "Burung Putih"
  , "Naga Merah"
  , "Kuda Emas"
  , "Serigala Putih"
  , "Harimau Emas"
  , "Burung Hijau"
  , "Ikan Emas"
  , "Kucing Putih"
  , "Ular Emas"
  , "Gajah Biru"
  , "Singa Putih"
  , "Kelinci Merah"
  , "Anjing Putih"
  , "Harimau Hijau"
  , "Burung Merah"
  , "Naga Biru"
  , "Kuda Merah"
  , "Serigala Hitam"
  , "Kelinci Biru"
  , "Ikan Hijau"
  , "Kucing Merah"
  , "Ular Hijau"
  , "Gajah Merah"
  , "Burung Biru"
  , "Naga Putih"
  , "Kuda Hijau"
  , "Serigala Merah"
  , "Harimau Biru"
  , "Burung Hitam"
  , "Ikan Biru"
  , "Kucing Hijau"
  , "Ular Merah"
  , "Gajah Putih"
  , "Singa Biru"
  , "Kelinci Hijau"
  , "Anjing Merah"
  , "Harimau Perak"
  , "Burung Perak"
  , "Naga Hijau"
  , "Kuda Biru"
  , "Serigala Hijau"
  , "Sandal Terbang"
  , "Mata Kucing"
  , , "Sapu Terbang"
  , , "Tongkat Perak"
  , , "Kalung Permata"
  , , "Gelang Emas"
  , , "Batu Kristal"
  , , "Kain Gaib"
  , , "Pedang Perak"
  , , "Sumpit Sakti"
  , , "Buku Sihir"
  , , "Pena Emas"
  , , "Cangkir Mistis"
  , , "Bantal Ajaib"
  , , "Batu Naga"
  , , "Lukisan Hidup"
  , , "Jam Sakti"
  , , "Cermin Gaib"
  , , "Cincin Gaib"
  , , "Gelang Mistis"
  , , "Jubah Sihir"
  , , "Kunci Ajaib"
  , , "Lilin Sakti"
  , , "Guci Mistis"
  , , "Obor Sihir"
  , , "Kipas Sakti"
  , , "Kendi Ajaib"
  , , "Permata Gaib"
  , , "Tas Mistis"
  , , "Batu Sihir"
  , , "Cawan Sakti"
  , , "Sumpit Emas"
  , , "Permadani Terbang"
  , , "Keris Emas"
  , , "Piring Gaib"
  , , "Guci Bertuah"
  , , "Cermin Sakti"
  , , "Kalung Gaib"
  , "Pedang Gaib"
  , "Kain Mistis"
  , "Tongkat Ajaib"
  , "Gelang Perak"
  , "Jubah Bertuah"
  , "Bunga Sihir"
  , "Permata Sakti"
  , "Topi Sihir"
  , "Sepatu Gaib"
  , "Sandal Ajaib"
  , "Mata Elang"
  , "Sapu Gaib"
  , "Tongkat Emas"
  , "Kalung Bertuah"
  , "Gelang Sakti"
  , "Batu Mistis"
  , "Kain Sihir"
  , "Pedang Bertuah"
  , "Sumpit Gaib"
  , "Buku Bertuah"
  , "Pena Sakti"
  , "Cangkir Gaib"
  , "Bantal Mistis"
  , "Batu Sihir"
  , "Lukisan Gaib"
  , "Jam Mistis"
  , "Cermin Ajaib"
  , "Cincin Sakti"
  , "Gelang Gaib"
  , "Jubah Emas"
  , "Kunci Sihir"
  , "Lilin Gaib"
  , "Guci Sakti"
  , "Obor Bertuah"
  , "Kipas Ajaib"
  , "Kendi Gaib"
  , "Permata Sihir"
  , "Tas Sihir"
  , "Batu Sakti"
  , "Cawan Ajaib"
  , "Sumpit Sihir"
  , "Permadani Bertuah"
  , "Keris Sihir"
  , "Piring Sihir"
  , "Guci Emas"
  , "Cermin Mistis"
  , "Kalung Bertuah"
  , "Pedang Mistis"
  , "Kain Sakti"
  , "Tongkat Sihir"
  , "Gelang Ajaib"
  , "Jubah Mistis"
  , "Bunga Ajaib"
  , "Permata Bertuah"
  , "Topi Bertuah"
  , "Sepatu Sihir"
  , "Sandal Gaib"
  , "Mata Harimau"
  , "Sapu Sakti"
  , "Tongkat Mistis"
  , "Kalung Sihir"
  , "Gelang Bertuah"
  , "Batu Ajaib"
  , "Kain Ajaib"
  , "Pedang Sihir"
  , "Sumpit Mistis"
  , "Buku Sihir"
  , "Pena Bertuah"
  , "Cangkir Ajaib"
  , "Bantal Bertuah"
  , "Batu Gaib"
  , "Lukisan Bertuah"
  , "Jam Gaib"
  , , "Cermin Bertuah"
  , , "Cincin Mistis"
  , , "Gelang Sihir"
  , , "Jubah Sakti"
  , , "Kunci Bertuah"
  , , "Lilin Ajaib"
  , , "Guci Gaib"
  , , "Obor Sihir"
  , , "Kipas Mistis"
  , , "Kendi Sakti"
  , , "Permata Mistis"
  , , "Tas Bertuah"]